import { act } from "react";
import { createRoot } from "react-dom/client";
import Login from "./Login";
import VerifyEmail from "./VerifyEmail";

const mockNavigate = jest.fn();
const mockLogin = jest.fn();
const mockPost = jest.fn();
const mockGet = jest.fn();
let mockLocationState = null;
let mockCapabilities;

jest.mock("react-router-dom", () => ({
  useNavigate: () => mockNavigate,
  useLocation: () => ({ state: mockLocationState }),
  Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
}), { virtual: true });

jest.mock("@/context/AuthContext", () => ({
  useAuth: () => ({ login: mockLogin }),
}));

jest.mock("@/lib/authCapabilities", () => ({
  ...jest.requireActual("@/lib/authCapabilities"),
  useAuthCapabilities: () => ({ loading: false, capabilities: mockCapabilities }),
}));

jest.mock("@/lib/api", () => ({
  api: {
    post: (...args) => mockPost(...args),
    get: (...args) => mockGet(...args),
  },
  errMsg: (error) => error?.response?.data?.detail?.message || error?.message || "Request failed",
  routeForUser: () => "/",
}));

jest.mock("sonner", () => ({
  toast: { success: jest.fn(), error: jest.fn(), info: jest.fn() },
}));

jest.mock("@/pages/auth/AuthShell", () => ({
  AuthShell: ({ children, title }) => <main><h1>{title}</h1>{children}</main>,
}));

jest.mock("@/components/ui/button", () => ({
  Button: ({ children, ...props }) => <button {...props}>{children}</button>,
}));

jest.mock("@/components/ui/input", () => ({ Input: (props) => <input {...props} /> }));
jest.mock("@/components/ui/label", () => ({ Label: ({ children, ...props }) => <label {...props}>{children}</label> }));
jest.mock("@/components/ui/input-otp", () => ({
  InputOTP: ({ value, onChange }) => (
    <input data-testid="verification-code-input" value={value} onChange={(event) => onChange(event.target.value)} />
  ),
  InputOTPGroup: ({ children }) => <>{children}</>,
  InputOTPSlot: () => null,
}));

function change(input, value) {
  act(() => {
    const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
    setter.call(input, value);
    input.dispatchEvent(new Event("input", { bubbles: true }));
  });
}

async function settle() {
  await Promise.resolve();
  await Promise.resolve();
  await Promise.resolve();
}

async function render(Component) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  await act(async () => {
    root.render(<Component />);
    await settle();
  });
  return { container, root };
}

async function submit(form) {
  await act(async () => {
    form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }));
    await settle();
  });
}

beforeAll(() => {
  global.IS_REACT_ACT_ENVIRONMENT = true;
});

beforeEach(() => {
  mockNavigate.mockReset();
  mockLogin.mockReset();
  mockPost.mockReset();
  mockGet.mockReset();
  mockLocationState = null;
  mockCapabilities = {
    registration_enabled: true,
    phone_registration: true,
    email_registration: false,
    phone_contact_verification: true,
    email_contact_verification: true,
    verification_required: true,
    email_verification_required: false,
    registration_mode: "PHONE_OTP",
  };
});

afterEach(() => {
  document.body.innerHTML = "";
  jest.clearAllMocks();
});

test("an auto-generated Login ID is not re-entered on verify", async () => {
  mockLocationState = {
    channel: "PHONE",
    identifier: "+447700900123",
    challengeId: "phone-challenge-1",
    secondaryIdentifier: "player@example.com",
    loginId: "p447700900123",
    loginIdAutoGenerated: true,
  };
  mockPost.mockResolvedValueOnce({ data: {
    access_token: "token",
    user: { id: "player-1", role: "PLAYER", status: "ACTIVE" },
  } });
  const { container, root } = await render(VerifyEmail);

  expect(container.querySelector('[data-testid="verify-login-id-input"]')).toBeNull();
  change(container.querySelector('[data-testid="verification-code-input"]'), "123456");
  change(container.querySelector('[data-testid="verify-password-input"]'), "Strong-Password-9");
  change(container.querySelector('[data-testid="verify-password-confirm-input"]'), "Strong-Password-9");
  await submit(container.querySelector("form"));

  expect(mockPost).toHaveBeenCalledWith("/auth/verify-otp", expect.objectContaining({
    channel: "PHONE",
    identifier: "+447700900123",
    username: "p447700900123",
  }));
  expect(mockLogin).toHaveBeenCalledWith("token", expect.objectContaining({ id: "player-1" }));
  await act(async () => root.unmount());
});

test("an email next_verification step is ignored after phone OTP", async () => {
  mockLocationState = {
    channel: "PHONE",
    identifier: "+447700900123",
    challengeId: "phone-challenge-1",
    secondaryIdentifier: "player@example.com",
    loginId: "Royal.Player",
  };
  mockPost.mockResolvedValueOnce({ data: {
    next_verification: {
      channel: "EMAIL",
      identifier: "player@example.com",
      verification_id: "email-challenge-2",
      destination_masked: "p***@example.com",
    },
  } });
  const { container, root } = await render(VerifyEmail);

  change(container.querySelector('[data-testid="verify-login-id-input"]'), "Royal.Player.2");
  change(container.querySelector('[data-testid="verification-code-input"]'), "123456");
  change(container.querySelector('[data-testid="verify-password-input"]'), "Strong-Password-9");
  change(container.querySelector('[data-testid="verify-password-confirm-input"]'), "Strong-Password-9");
  await submit(container.querySelector("form"));

  expect(mockPost).toHaveBeenCalledTimes(1);
  expect(mockPost).toHaveBeenCalledWith("/auth/verify-otp", expect.objectContaining({
    channel: "PHONE",
    identifier: "+447700900123",
    challenge_id: "phone-challenge-1",
    verification_id: "phone-challenge-1",
    username: "Royal.Player.2",
  }));
  expect(mockLogin).not.toHaveBeenCalled();
  expect(mockNavigate).toHaveBeenCalledWith("/?auth=login", { replace: true });
  await act(async () => root.unmount());
});

test("login recovery resends SMS to the stored mobile after a Login ID login", async () => {
  mockPost.mockRejectedValueOnce({ response: { data: { detail: {
    code: "CONTACT_NOT_VERIFIED",
    channel: "PHONE",
    identifier: "+919876543210",
    login_id: "Lobby.Player",
    message: "Verify your contact method before logging in.",
  } } } });
  mockGet.mockResolvedValue({ data: {
    registration_enabled: true,
    phone_registration: true,
    email_registration: false,
    phone_contact_verification: true,
    email_contact_verification: true,
    verification_required: true,
    email_verification_required: false,
    registration_mode: "PHONE_OTP",
  } });
  mockPost.mockResolvedValueOnce({ data: {
    challenge_id: "login-phone-challenge",
    verification_id: "login-phone-challenge",
    destination_masked: "+91******10",
    resend_after_seconds: 60,
  } });
  const { container, root } = await render(Login);
  change(container.querySelector("#identifier"), "Lobby.Player");
  change(container.querySelector("#password"), "Lobby-Player-9");
  await submit(container.querySelector("form"));

  expect(mockPost).toHaveBeenCalledWith("/auth/resend-otp", expect.objectContaining({
    channel: "PHONE",
    identifier: "+919876543210",
    phone: "+919876543210",
  }));
  expect(mockNavigate).toHaveBeenCalledWith("/verify", expect.objectContaining({
    state: expect.objectContaining({
      channel: "PHONE",
      identifier: "+919876543210",
      challengeId: "login-phone-challenge",
      loginId: "Lobby.Player",
    }),
  }));
  await act(async () => root.unmount());
});

test("login recovery does not send PHONE_OTP players into email OTP", async () => {
  mockPost.mockRejectedValueOnce({ response: { data: { detail: {
    code: "CONTACT_NOT_VERIFIED",
    channel: "EMAIL",
    identifier: "player@example.com",
    login_id: "Royal.Player.2",
    message: "Verify your contact method before logging in.",
  } } } });
  mockGet.mockResolvedValue({ data: {
    registration_enabled: true,
    phone_registration: true,
    email_registration: false,
    phone_contact_verification: true,
    email_contact_verification: true,
    verification_required: true,
    email_verification_required: false,
    registration_mode: "PHONE_OTP",
  } });
  const { container, root } = await render(Login);
  change(container.querySelector("#identifier"), "+447700900123");
  change(container.querySelector("#password"), "Strong-Password-9");
  await submit(container.querySelector("form"));

  expect(mockPost).toHaveBeenCalledTimes(1);
  expect(mockPost).not.toHaveBeenCalledWith("/auth/resend-otp", expect.anything());
  expect(mockNavigate).not.toHaveBeenCalledWith("/verify", expect.anything());
  await act(async () => root.unmount());
});

test("verification rejects a six-character nonnumeric code before calling the API", async () => {
  mockLocationState = {
    channel: "PHONE",
    identifier: "+447700900123",
    challengeId: "phone-challenge-3",
    loginId: "Royal.Player",
  };
  const { container, root } = await render(VerifyEmail);

  change(container.querySelector('[data-testid="verification-code-input"]'), "12AB56");
  change(container.querySelector('[data-testid="verify-password-input"]'), "Strong-Password-9");
  change(container.querySelector('[data-testid="verify-password-confirm-input"]'), "Strong-Password-9");
  await submit(container.querySelector("form"));

  expect(mockPost).not.toHaveBeenCalled();
  expect(container.querySelector('[data-testid="verify-email-submit-button"]').disabled).toBe(true);
  await act(async () => root.unmount());
});
