import { useEffect, useState } from "react";
import { REGEXP_ONLY_DIGITS } from "input-otp";
import { Link, useNavigate, useLocation } from "react-router-dom";
import { toast } from "sonner";
import { AlertTriangle, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { Label } from "@/components/ui/label";
import { api, errMsg, routeForUser } from "@/lib/api";
import { normalizeContactChannel, normalizeContactIdentifier, registrationChannelAvailable, useAuthCapabilities, verificationChannelState } from "@/lib/authCapabilities";
import { useAuth } from "@/context/AuthContext";
import { AuthShell } from "@/pages/auth/AuthShell";

const DEFAULT_RESEND_SECONDS = 60;

export default function VerifyEmail() {
  const navigate = useNavigate();
  const location = useLocation();
  const { login } = useAuth();
  const { capabilities, loading: capabilitiesLoading } = useAuthCapabilities();
  const initial = location.state || {};
  const issuedChallenge = Boolean(initial.identifier || initial.email);
  const [channel, setChannel] = useState(normalizeContactChannel(initial.channel || "PHONE", initial.identifier || initial.email));
  const [identifier, setIdentifier] = useState(initial.identifier || initial.email || "");
  const [challengeId, setChallengeId] = useState(
    initial.challengeId || initial.challenge_id || initial.verificationId || initial.verification_id || "",
  );
  const [secondaryIdentifier] = useState(initial.secondaryIdentifier || "");
  const [loginId, setLoginId] = useState(initial.loginId || "");
  const loginIdAutoGenerated = Boolean(initial.loginIdAutoGenerated);
  const showLoginIdField = Boolean(initial.loginId) && !loginIdAutoGenerated;
  const [destinationMasked, setDestinationMasked] = useState(initial.destinationMasked || "");
  const [code, setCode] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [resending, setResending] = useState(false);
  const [resendIn, setResendIn] = useState(Number(initial.resendAfter || 0));

  useEffect(() => {
    if (resendIn <= 0) return undefined;
    const timer = window.setInterval(() => setResendIn((value) => Math.max(0, value - 1)), 1000);
    return () => window.clearInterval(timer);
  }, [resendIn]);

  useEffect(() => {
    if (issuedChallenge || capabilitiesLoading || registrationChannelAvailable(capabilities, channel)) return;
    if (registrationChannelAvailable(capabilities, "PHONE")) setChannel("PHONE");
  }, [capabilities, capabilitiesLoading, channel, issuedChallenge]);

  const {
    deliveryAvailable: selectedChannelAvailable,
    verificationAvailable,
    anyChannelAvailable,
  } = verificationChannelState(capabilities, channel, issuedChallenge);
  // An OTP that has already been delivered remains verifiable if delivery is
  // later paused. Only direct-entry verification and resend require a live
  // delivery channel.

  const normalizedIdentifier = () => normalizeContactIdentifier(channel, identifier);

  const submit = async (event) => {
    event?.preventDefault();
    if (!verificationAvailable) return toast.info("Verification is temporarily unavailable for this contact method.");
    if (!identifier.trim()) return toast.error(`Enter your ${channel === "PHONE" ? "mobile number" : "email"}`);
    if (showLoginIdField && !/^[A-Za-z0-9][A-Za-z0-9._-]{3,31}$/.test(loginId.trim())) return toast.error("Start your Login ID with a letter or number; use 4–32 letters, numbers, dots, underscores, or hyphens");
    if (!/^\d{6}$/.test(code)) return toast.error("Enter the 6-digit code");
    if (password.length < 8) return toast.error("Password must be at least 8 characters");
    if (password !== confirmPassword) return toast.error("Passwords do not match");
    setBusy(true);
    try {
      const contact = normalizedIdentifier();
      const { data } = await api.post("/auth/verify-otp", {
        channel,
        identifier: contact,
        email: channel === "EMAIL" ? contact : undefined,
        phone: channel === "PHONE" ? contact : undefined,
        username: loginId.trim() || undefined,
        challenge_id: challengeId || undefined,
        verification_id: challengeId || undefined,
        code,
        password,
      });
      if (data?.next_verification) {
        const next = data.next_verification;
        const nextChannel = normalizeContactChannel(next.channel || "EMAIL", secondaryIdentifier);
        if (nextChannel === "EMAIL") {
          // Phone SMS is the only activation proof. Ignore leftover email OTP steps.
          if (data.access_token) {
            login(data.access_token, data.user);
            toast.success(data.message || "Mobile verified");
            navigate(routeForUser(data.user), { replace: true });
          } else {
            toast.success(data.message || "Mobile verified. You can now log in.");
            navigate("/login", { replace: true });
          }
          return;
        }
        const nextIdentifier = secondaryIdentifier || next.identifier || "";
        if (!nextIdentifier) {
          toast.success("Mobile verified. You can now log in.");
          navigate("/login", { replace: true });
          return;
        }
        setChannel(nextChannel);
        setIdentifier(nextIdentifier);
        setChallengeId(next.challenge_id || next.verification_id || "");
        setDestinationMasked(next.destination_masked || next.destination || "");
        setResendIn(Number(next.resend_after_seconds || next.resend_in || DEFAULT_RESEND_SECONDS));
        setCode("");
        toast.success(data.message || "Mobile verified");
        return;
      }
      if (data.access_token) {
        login(data.access_token, data.user);
        toast.success("Contact verified");
        navigate(routeForUser(data.user), { replace: true });
      } else {
        toast.success(data.message || "Contact verified. You can now log in.");
        navigate("/login", { replace: true });
      }
    } catch (error) {
      toast.error(errMsg(error));
    } finally {
      setBusy(false);
    }
  };

  const resend = async () => {
    if (capabilitiesLoading || !selectedChannelAvailable) return toast.info("Sending a new code is temporarily unavailable for this contact method.");
    if (!identifier.trim()) return toast.error("Enter your contact details first");
    setResending(true);
    try {
      const contact = normalizedIdentifier();
      const { data } = await api.post("/auth/resend-otp", {
        channel,
        identifier: contact,
        email: channel === "EMAIL" ? contact : undefined,
        phone: channel === "PHONE" ? contact : undefined,
      });
      setDestinationMasked(data.destination_masked || destinationMasked);
      setChallengeId(data.challenge_id || data.verification_id || "");
      setResendIn(Number(data.resend_after_seconds || DEFAULT_RESEND_SECONDS));
      setCode("");
      toast.success(data.message || "If an unverified account matches, a new code has been requested");
    } catch (error) {
      if (error?.response?.status === 429) {
        const retryAfter = Number(error?.response?.headers?.["retry-after"] || DEFAULT_RESEND_SECONDS);
        setResendIn(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : DEFAULT_RESEND_SECONDS);
      }
      toast.error(errMsg(error));
    } finally {
      setResending(false);
    }
  };

  const destination = destinationMasked || identifier || (channel === "PHONE" ? "your mobile" : "your email");

  if (!capabilitiesLoading && capabilities.registration_mode === "ADMIN_REVIEW" && !issuedChallenge) {
    return (
      <AuthShell title="Administrator review" subtitle="Contact OTP is not part of the current registration flow." backTo="/register">
        <div className="rounded-xl border border-amber-300/25 bg-amber-300/8 p-4 text-sm leading-relaxed text-amber-100">
          Enter your email, mobile number and password on the registration page. An administrator must approve the account before you can log in and play.
        </div>
        <Button type="button" onClick={() => navigate("/register")} className="mt-5 h-12 w-full rounded-xl font-bold">
          Go to registration
        </Button>
      </AuthShell>
    );
  }

  return (
    <AuthShell title="Verify your account" subtitle={`Enter the 6-digit code issued for ${destination}.`} backTo="/register">
      {!issuedChallenge && !capabilitiesLoading && !anyChannelAvailable && (
        <div data-testid="verification-unavailable" className="mb-5 flex items-start gap-2.5 rounded-xl border border-amber-300/25 bg-amber-300/8 p-3 text-xs leading-relaxed text-amber-100">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />
          <span><strong>Verification is temporarily unavailable.</strong> Mobile code delivery is not currently ready. Please try again later.</span>
        </div>
      )}
      {issuedChallenge && !capabilitiesLoading && !selectedChannelAvailable && (
        <div data-testid="verification-resend-unavailable" className="mb-5 flex items-start gap-2.5 rounded-xl border border-amber-300/25 bg-amber-300/8 p-3 text-xs leading-relaxed text-amber-100">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />
          <span>Your delivered code can still be verified, but sending a new code is temporarily unavailable.</span>
        </div>
      )}
      {!initial.identifier && !initial.email && (
        <div className="space-y-3 mb-5">
          <div className="flex h-10 items-center justify-center gap-2 rounded-xl border border-primary/55 bg-primary/12 text-sm font-semibold text-primary">
            <Smartphone className="h-4 w-4" /> Mobile OTP verification
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="verify-identifier">Mobile number (enter with +country code)</Label>
            <Input id="verify-identifier" data-testid="verify-identifier-input" disabled={capabilitiesLoading || !selectedChannelAvailable} type="tel" inputMode="tel" autoComplete="tel" placeholder="Enter with +country code" value={identifier} onChange={(event) => setIdentifier(event.target.value)} className="h-12 rounded-xl bg-white/5 border-white/12" />
          </div>
        </div>
      )}
      <form onSubmit={submit} className="space-y-5">
        {showLoginIdField && (
          <div className="space-y-1.5">
            <Label htmlFor="verify-login-id">Your Login ID</Label>
            <Input id="verify-login-id" data-testid="verify-login-id-input" type="text" autoComplete="username" autoCapitalize="none" spellCheck={false} required minLength={4} maxLength={32} value={loginId} onChange={(event) => setLoginId(event.target.value)} className="h-12 rounded-xl bg-white/5 border-white/12" />
            <p className="text-[11px] leading-relaxed text-white/45">You can change it before verification if the ID becomes unavailable.</p>
          </div>
        )}
        <div data-testid="verify-email-otp" className="flex justify-center">
          <InputOTP maxLength={6} pattern={REGEXP_ONLY_DIGITS} value={code} onChange={setCode}>
            <InputOTPGroup className="gap-2">
              {[0, 1, 2, 3, 4, 5].map((index) => <InputOTPSlot key={index} index={index} className="h-12 w-11 rounded-xl border-white/15 bg-white/5 text-lg" />)}
            </InputOTPGroup>
          </InputOTP>
        </div>
        <div className="space-y-1.5">
          <label htmlFor="verify-password" className="text-sm font-medium">Create your password</label>
          <Input id="verify-password" data-testid="verify-password-input" type="password" autoComplete="new-password" required minLength={8} placeholder="At least 8 characters" value={password} onChange={(event) => setPassword(event.target.value)} className="h-12 rounded-xl bg-white/5 border-white/12" />
          <p className="text-[11px] leading-relaxed text-white/45">For your security, the password is saved only after this code proves you own the contact method.</p>
        </div>
        <div className="space-y-1.5">
          <label htmlFor="verify-password-confirm" className="text-sm font-medium">Confirm password</label>
          <Input id="verify-password-confirm" data-testid="verify-password-confirm-input" type="password" autoComplete="new-password" required minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="h-12 rounded-xl bg-white/5 border-white/12" />
        </div>
        <Button data-testid="verify-email-submit-button" type="submit" disabled={busy || resending || !verificationAvailable || !/^\d{6}$/.test(code) || password.length < 8 || password !== confirmPassword} className="w-full h-12 rounded-xl text-base font-bold">
          {busy ? "Verifying…" : "Verify account"}
        </Button>
      </form>
      <button data-testid="verify-email-resend-button" type="button" onClick={resend} disabled={busy || resending || resendIn > 0 || capabilitiesLoading || !selectedChannelAvailable} className="mt-5 text-sm text-primary font-semibold hover:underline disabled:text-white/35 disabled:no-underline">
        {resending ? "Sending…" : resendIn > 0 ? `Send a new code in ${resendIn}s` : "Send a new code"}
      </button>
      <div data-testid="verification-recovery-guidance" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-relaxed text-white/60">
        <p>
          {channel === "PHONE"
            ? "No SMS? Confirm the number starts with +country code. If these details were registered before, use login or account recovery instead."
            : "No email? Check spam or junk. If these details were registered before, use login or account recovery instead."}
        </p>
        <div className="mt-2 flex gap-4 font-semibold text-primary">
          <Link to="/login" className="hover:underline">Log in</Link>
          <Link to="/forgot-password" className="hover:underline">Forgot password</Link>
        </div>
      </div>
    </AuthShell>
  );
}
